esercizio6.0: Esercizio6.0.o Particella.o
	g++ Esercizio6.0.o Particella.o -o esercizio6.0

Esercizio6.0.o: Esercizio6.0.cpp Particella.h 
	g++ -c Esercizio6.0.cpp -o Esercizio6.0.o

Particella.o: Particella.cpp Particella.h
	g++ -c Particella.cpp -o Particella.o

clean:
	rm *.o
	rm esercizio6.0
